Revert "HSI: ssi_protocol: Fix use after free vulnerability in ssi_protocol Driver Due to Race Condition"
This reverts commit 5e40d64e57eb4520df94f529f250f18d062de5ec.

Causes build failures:

```
drivers/hsi/clients/ssi_protocol.c: In function 'ssip_reset':
drivers/hsi/clients/ssi_protocol.c:413:30: error: 'struct ssi_protocol' has no member named 'work'
  413 |         cancel_work_sync(&ssi->work);
      |                              ^~
make[3]: *** [scripts/Makefile.build:286: drivers/hsi/clients/ssi_protocol.o] Error 1
```

Reported-by: Nobuhiro Iwamatsu <nobuhiro.iwamatsu.x90@mail.toshiba>
Signed-off-by: Ulrich Hecht <uli@kernel.org>