Revert "media: omap3isp: use sgtable-based scatterlist wrappers"
This reverts commit c547946f8c82643ea765319a4585c5619e84ee51.

Causes build failures:

```
drivers/media/platform/omap3isp/ispstat.c: In function 'isp_stat_buf_sync_for_device':
drivers/media/platform/omap3isp/ispstat.c:164:9: error: implicit declaration of function 'dma_sync_sgtable_for_device'; did you mean 'dma_sync_single_for_device'? [-Werror=implicit-function-declaration]
  164 |         dma_sync_sgtable_for_device(stat->isp->dev, &buf->sgt, DMA_FROM_DEVICE);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         dma_sync_single_for_device
```

Reported-by: Nobuhiro Iwamatsu <nobuhiro.iwamatsu.x90@mail.toshiba>
Signed-off-by: Ulrich Hecht <uli@kernel.org>