Revert "firmware: arm_scpi: Check the DVFS OPP count returned by the firmware"
This reverts commit 089553788f5f1fd84bcda8e3b2a4ed389f3b77d8.

Causes build failures:

```
[...]
drivers/firmware/arm_scpi.c: In function 'scpi_dvfs_get_info':
drivers/firmware/arm_scpi.c: In function 'scpi_dvfs_get_info':
drivers/firmware/arm_scpi.c:475:17: error: 'struct dvfs_info' has no member named 'pp_count'
  475 |         if (!buf.opp_count)
        |                 ^

  CC      drivers/dma/lpc18xx-dmamux.o
make[2]: *** [scripts/Makefile.build:280: drivers/firmware/arm_scpi.o] Error 1
make[1]: *** [scripts/Makefile.build:487: drivers/firmware] Error 2
make[1]: *** Waiting for unfinished jobs....
[...]
```

Reported-by: Nobuhiro Iwamatsu <nobuhiro.iwamatsu.x90@mail.toshiba>
Signed-off-by: Ulrich Hecht <uli@kernel.org>