Revert "watchdog: bcm2835_wdt: Fix WDIOC_SETTIMEOUT handling"
This reverts commit 65e5abd22423bcb8597ee3d8213977a182916f52.

Causes build failures:

```
  CC [M]  drivers/watchdog/bcm2835_wdt.o
drivers/watchdog/bcm2835_wdt.c:119:10: error: 'struct watchdog_device' has no member named 'max_hw_heartbeat_ms'
  119 |         .max_hw_heartbeat_ms =  WDOG_TICKS_TO_MSECS(PM_WDOG_TIME_SET),
      |          ^~~~~~~~~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:286: drivers/watchdog/bcm2835_wdt.o] Error 1
make[1]: *** [scripts/Makefile.build:487: drivers/watchdog] Error 2
```

Reported-by: Nobuhiro Iwamatsu <nobuhiro.iwamatsu.x90@mail.toshiba>
Signed-off-by: Ulrich Hecht <uli@kernel.org>